### ISSUE TITLE
Deal with `\reversemarginpar\marginnote{....}\hypertarget{....}{}` in equations

### ISSUE THREAD

**Issue by pbelmans** [gerby-project/plastex#11]
The Stacks project generates the following TeX code

```tex
\begin{equation}
\label{more-algebra-equation-define-M}
\reversemarginpar\marginnote{0BP3}\hypertarget{0BP3}{}
0 \to M \to M' \oplus M_1 \to (M')_f \to 0.
\end{equation}
```

We should deal with this, as we just dump `{{ obj.source }}` to MathJax right now, and MathJax doesn't recognise these commands. Maybe the following snippet from the manual contains a possible solution:

> However, you can also return a list of tokens. If a list of tokens is returned, instead of the macro instance, those tokens are inserted into the output stream. This is useful if you don’t want the macro instance to be part of the output stream or document. In this case, you can simply return an empty list.

**Comment by PatrickMassot** [comment]
I don't think using the digest method with empty list return value will change the source code used during math rendering.

A more flexible workaround is to have a separate preamble for plasTeX compilation where you simply redefine these commands to do nothing. There you would see:
```latex
\def\reversemarginpar{}
\newcommand{\marginnote}[1]{}
\newcommand{\hypertarget}[2]{}
```

The reason why I'm using ``\def`` instead of ``\renewcommand`` above is a plasTeX bug I just discovered while writing this answer, see [this issue](https://github.com/tiarno/plastex/issues/90).

**Comment by pbelmans** [comment]
Ah, excellent solution. Especially because it's only the Stacks project which wants to do something like this anyway, and we can safely ignore these in HTML. Thanks for the suggestion, and explaining this plasTeX idiosyncracy!
