### ISSUE TITLE
XyJax issues

### ISSUE THREAD

**Issue by pbelmans** [gerby-project/plastex#18]
We should still do this headless browser thing to test for these errors automatically. Anyway, the following tags have XyJax issues (where the current website does _not_):

- [x] 0145

**Comment by aisejohan** [comment]
Strange issue with tag 0BH9 where there is a reversemarginpar which doesn't belong there. Probably due to having an old database?

**Comment by pbelmans** [comment]
You are right! I'm updating it right now.

**Comment by aisejohan** [comment]
Seems equations still have reversemarginpar after the update

**Comment by pbelmans** [comment]
Dammit, I forgot to include the fix suggested in #11. Rerunning the script, hang on a while.

**Comment by pbelmans** [comment]
Okay, it took a while, but the `\reversemarginpar` issue is now fixed in the live database, and I documented all [the necessary steps here](http://pbelmans.ncag.info/blog/2017/08/27/introduction-gerby-plastex/).

The issue on tag 0145 remains, as expected.

**Comment by chngr** [comment]
Commit 8498571 fixes the parsing issue on tag 0145. The issue was that the plastex automatically replaces text patterns like ``--`` with their unicode counterpart, which, in this case is a unicode endash. See the lines 785 to 802 [here](https://github.com/pbelmans/plastex/blob/8672726ae9cf48b2c091fda0f78a56110b47b444/plasTeX/__init__.py#L785-L802) for the patterns plastex replaces.

Now, in tag 0145, the ``xymatrix`` had a dashed arrow, and this is given by ``\ar@[-->]``. So when plastex parsed the command, it saw the ``--`` pattern, replaced it with a unicode endash, consequently confusing ``xy.js``.

**Comment by pbelmans** [comment]
Awesome, thanks for figuring this out!

**Comment by chngr** [comment]
Let's close this issue and move discussion to #21?
