### ISSUE TITLE
Redundant <p>'s in environments with paragraphs

### ISSUE THREAD

**Issue by pbelmans** [gerby-project/plastex#38]
Check out tag 0092 or 00JF. We shouldn't start a new paragraph in the beginning of the statement.

**Comment by pbelmans** [comment]
This might be a duplicate of #31 actually.

**Comment by chngr** [comment]
The issue here is due to 0092 and 00JF having multiple paragraphs. Perhaps rather strangely, when a Theorem Environment only has a single paragraph, plasTeX does not wish to enclose this unique paragraph in a `par` element and will just keep the parsed object as a list of its constituents. Thus the Jinja2 template works fine for such objects. But when the Theorem Environment does have multiple paragraphs, the raw object then becomes a list of paragraphs, so when it is rendered, extra paragraph elements are printed.

One way to fix this is to force Theorem Environments to always make paragraphs. This can be done by including `'forcePars': True` in the class options within `class newtheorem` found in `Base/LaTeX/Definitions.py`. With this, a slight modification of the Jinja2 `thmenv` template is required, but it basically is a copy of the `proof` template I wrote before. I am testing this to make sure this does not cause further issues.

**Comment by aisejohan** [comment]
OK, I'm afraid this caused there to be a problem with reference environments in lemmas. In my local setup after running plastex and updating the database I get a problem on tags `005P` and `005R`. The problem appears to be that the reference environment remains in the statement of the lemma whereas before it wasn't there...

Just to make sure, in the book.tex file (gotten using the `make web` target in Makefile of the `web` branch of my personal version of `stacks-project`) using the `\begin{reference}...\end{reference}` environments are left in and the reference environment is not defined away in the preamble. This is according to some instructions of Pieter a while back.

**Comment by chngr** [comment]
Oh indeed. Looks like the issue is that the `reference` element (and other types of elements, for that matter...) is encased in a `par` element, and so the code in [lines 68 to 75](https://github.com/pbelmans/plastex/blob/d86619e7b8784fb64eb3d9dcab7556467d734196/plasTeX/Renderers/Gerby/__init__.py#L68-L75) in `plastex/Renderers/Gerby/__init__.py` cannot find the element. I will fix this tomorrow, and, along the way, hopefully address some of the technical debt that is piled up there. I will create a new issue to recall this.
