### ISSUE TITLE
`\hyperref` not working

### ISSUE THREAD

**Issue by pbelmans** [gerby-project/plastex#53]
As per Daniel Litt's comment https://stacks.math.columbia.edu/tag/06LB#comment-3384.

An example of the offending code is
```
\item Jarod Alper wrote
\hyperref[guide-section-phantom]{Guide to Literature}.
```

Right now we just send `hyperref` to the empty output in `Misc.jinja2s`. Page 15 of the hyperref manual lists 2 versions of the `\hyperref` macro, but `hyperref.py` only implements the second (which is the one used in the Stacks project).

Presumably it's enough to just implement the macro then.

**Comment by pbelmans** [comment]
We could resolve these labels in plasTeX to tags, and then insert links to the tag pages.

Alternatively, and much easier, we just rewrite the 4 items on the linked page to use the format of the other items, which do use the standard referencing scheme for the Stacks project.

What do you say, @aisejohan?

**Comment by aisejohan** [comment]
You know, this is just something that has been there since 2013. I guess it is now time to change it... Will  to do it in the stacks project. I never did it before because there is no elegant way to refer to chapters in the stacks project (inside the pdfs with all the unwritten rules I have in place -- you'll see).

**Comment by aisejohan** [comment]
This issue can be closed now but I don't have the permissions to close it.

**Comment by pbelmans** [comment]
Now you do, but let me still close this one.
