### ISSUE TITLE
Question: Is this fork radically different from plastex/plastex original project?

### ISSUE THREAD

**Issue by federerfanatic** [gerby-project/plastex#59]
Hi, I am little confused as to which project I should be using to convert my LaTeX project into
a web viewable form with all the benefit of Jacob Lurie's Keradon and the Stacks project. My apologies for asking a, possibly, silly question.

FF
 
In your README you have  http://tiarno.github.io/plastex/ which gives a 404 error, which is why I was motivated to ask the question above.

**Comment by PatrickMassot** [comment]
The dead url should be http://plastex.github.io/plastex/. 

What you want is indeed the Gerby project, which uses plasTeX to build a certain kind of website. The situation would be much clearer if Gerby used plasTeX as a library instead of being of fork of plasTeX. But the current setup was more convenient in the early days of the Gerby project when they were exploring plasTeX and needed to really quickly try small modifications to plasTeX. And then everybody was busy, both on the plasTeX and Gerby sides, and this confusion follows. One day this will be fixed...

**Comment by federerfanatic** [comment]
Thanks. It would seem there are many programs that attempt to solve the
problem of publishing
mathematics on the WWW. I am fond of pandoc to a degree as it quite good at
fetching websites
and convert that to an epub and then that to latex.

FF



--------------------------------------------------------------
 Roger Federer Fanatic Extraordinaire :-)

**Comment by pbelmans** [comment]
This is the repository one needs for using Gerby (as explained on https://gerby-project.github.io). I will fix the URLs, and once the semester is over here I want to make the situation a bit more clear regarding plasTeX versus the Gerby fork (which like Patrick explained, should rather be an add-on, instead of a fork, but this was much easier for development).
